# Enable or disable SXP bottle and book commands
enable-bottles: true
enable-books: true

# Enable or disable Mending Repair when SXP item is used
enable-mending: true

# Max XP levels allowed in a single bottle or book (set to -1 for no limit)
max-xp-levels-bottle: 1000
max-xp-levels-book: 5000

# Enable or disable Debug mode (use if there are issues with the plugin, this should help pinpoint issues)
debug-mode: false

# Worlds where players CANNOT redeem SXP bottles/books.
# Put world names here (case-insensitive).
# Example:
# blocked-redeem-worlds:
#   - world_nether
#   - world_the_end
blocked-redeem-worlds: []
